<?php

declare(strict_types=1);

/** @var \MageOS\Blog\Block\Post\Listing $block */
/** @var \Magento\Framework\Escaper $escaper */

use MageOS\Blog\Api\Data\PostInterface;
use MageOS\Blog\ViewModel\Post\Listing as PostListing;

/** @var PostInterface $post */
$post = $block->getData('post');
/** @var PostListing $viewModel */
$viewModel = $block->getData('view_model');
?>
<li class="mageos-blog-listing__item">
    <article>
        <h2 class="mageos-blog-listing__item-title">
            <a href="<?= $escaper->escapeUrl($viewModel->getPostUrl($post)); ?>">
                <?= $escaper->escapeHtml($post->getTitle()); ?>
            </a>
        </h2>
        <?php $date = $viewModel->getFormattedPublishDate($post); ?>
        <?php if ($date !== ''): ?>
            <p class="mageos-blog-listing__item-date"><?= $escaper->escapeHtml($date); ?></p>
        <?php endif; ?>
        <?php if ($post->getShortContent()): ?>
            <div class="mageos-blog-listing__item-excerpt">
                <?= /** @noEscape */ $post->getShortContent(); ?>
            </div>
        <?php endif; ?>
        <a href="<?= $escaper->escapeUrl($viewModel->getPostUrl($post)); ?>" class="mageos-blog-listing__item-more">
            <?= $escaper->escapeHtml(__('Read more →')); ?>
        </a>
    </article>
</li>
